### ISSUE TITLE
updating the name

### ISSUE THREAD

**Issue by hbeale** [UCSC-Treehouse/SeqGroom#1]
I noticed that the output still reports "bam2fq_mainloop". @jackieroger please update.

**Comment by jackieroger** [comment]
@hbeale the "bam2fq_mainloop" is printed when samtools fastq is called. I'm pretty sure that samtools fastq used to be called samtools bam2fq and this output text is leftover from that. (Tldr: it's not a seqgroom issue)

**Comment by hbeale** [comment]
great! thanks.
